feat: logger to format to google cloud structured logging
TeamMomentum/go-pkg pull request #2
Opened 2023-02-24 02:51 UTC by ynn1e

ログを GoogleCloud の構造化ロギングエントリにフォーマットして出力するパッケージを作成しました。

ref: https://cloud.google.com/logging/docs/structured-logging

2023-02-24 03:03 UTC, dictav commented on gcloud/logging/structured_logging.go
> +}
trace と span など、未サポートな点項目についてコメントお願いできますか？

2023-02-24 03:07 UTC, dictav commented
`log.Printf` の差し替えがしやすいように `logging.Println` と `logging.Printf` もあった方が良いと思うのですが、いかがでしょうか？
ついでに　`logging.Errorf` もほしいです。

2023-02-24 03:15 UTC, dictav commented on gcloud/logging/example/main.go
> +	entry := lg.New()
オリジナルのコードが間違っていると思うんですが、ここで定義して HandleFunc の中で使うのは良くないです。

あと、examples は消して良いかなと思いました。
README を作って README に以下のように書いておけば十分かなと思いました。

```go
http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
	entry := lg.New()
	entry.SetHTTPRequest(r)
	entry.SetLabels(map[string]string{
		"key1": "value1",
		"key2": "value2",
	})
	entry.SetLabelFunc("key3", func(v string) string {
		_, _, line, _ := runtime.Caller(3)
		return fmt.Sprintf("this is %s at %d", v, line)
	})

	entry.Debugf("received an HTTP request")

	entry.Infof("finished func")
})
```

2023-02-24 03:23 UTC, dictav commented on gcloud/logging/structured_logging.go
> +		log.SetFlags(0)
これを共通ライブラリでやっちゃうのは良くなさそうです。
以下のように defaultLogger を使うのはいかがでしょうか？

```go
var defaultLogger = log.New(os.Stderr, "", 0)

func SetOutput(o io.Writer) {
  defaultLogger.SetOutput(o)
}

func SetPrefix...
func SetFlags...
```

2023-02-24 08:00 UTC, ynn1e commented on gcloud/logging/structured_logging.go
> +		log.SetFlags(0)
@dictav 
New を無くし、labels などの Entry フィールドも defaultLabels のようにグローバルで定義するのはどうでしょうか？
その場合、メソッドも関数にしようと考えています。

```go
func (e *Entry) SetLabel(k, v string) {...}
```

```go
func SetEntryLabel(k, v string) {...}
```

2023-02-24 08:02 UTC, dictav commented on gcloud/logging/structured_logging.go
> +		log.SetFlags(0)
リクエスト毎に新しい Entry は作成したいので、全部を `default*` に置き換えることはできないんですよ

2023-02-24 08:04 UTC, ynn1e commented on gcloud/logging/structured_logging.go
> +}
@dictav 
他のフィールドをどのように使うかに関して調査と利用想定が私にとって不十分だったため現在はサポート外としていました。
もう少しどのフィールドが必要になりそうかを考えたいのですが、もし必要だと思われるフィールドがあれば教えていただけますでしょうか？

2023-02-24 08:12 UTC, dictav commented on gcloud/logging/structured_logging.go
> +		log.SetFlags(0)
Entry を隠蔽して全部 `func Println(s string, opts ...Option)` のように毎回指定するような実装も考えられますが、そうすると利用するプログラム側で引数を取り回さないといけなくなります。
そのような実装もやってみたんですが、個人的には使いにくかったです。

2023-02-24 08:16 UTC, dictav commented on gcloud/logging/structured_logging.go
> +		log.SetFlags(0)
> 以下のように defaultLogger を使うのはいかがでしょうか？

defaultLogger だと変更が許されているように見えますね。
個人的にはここは変更できる必要はないと思うので、 `logger` とか `out` とかの方が良いかな。
標準 log パッケージでは `std = New(os.Stderr, ...` みたいにしてますね

2023-02-24 08:24 UTC, dictav commented on gcloud/logging/structured_logging.go
> +}
んー、logEntry であえて項目を絞る必要はないんじゃないですかね？
https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry をきちんと射影しておいた方が良いと思います。

また、ユーザが使いたいと思ったら、非推奨の項目以外は使えるようにしておいた方が良いと思います。

2023-02-24 08:44 UTC, ynn1e commented on gcloud/logging/structured_logging.go
> +		log.SetFlags(0)
ありがとうございます。
標準パッケージに合わせた実装をベースに考えてみます。

2023-03-01 06:44 UTC, dictav commented on gcloud/logging/example/main.go
> +package main
READMEに書いてあるので、 example/ ディレクトリは不要かと思います

2023-03-01 06:49 UTC, dictav commented on gcloud/logging/structured_logging.go
> +func (e *entry) String() string {
この関数の用途はなんですか？
Stringerにする必要はなさそうだと思いました。

Logger.printf の中で json.Marshal すれば良いのではないでしょうか？

2023-03-01 06:55 UTC, dictav commented on gcloud/logging/structured_logging.go
> +		lg.entry.HTTPRequest = &ltype.HttpRequest{
https://pkg.go.dev/google.golang.org/genproto/googleapis/logging/type#HttpRequest

- RequestSize
- ServerIP
- UserAgent
- Referer

この辺はあった方が良さそうですが、省いた理由ってありますか？

2023-03-02 01:25 UTC, ynn1e commented on gcloud/logging/structured_logging.go
> +		lg.entry.HTTPRequest = &ltype.HttpRequest{
失念していました。
修正します。

2023-03-07 00:39 UTC, dictav approved these changes
LGTM!

2023-03-07 03:15 UTC, t4110 requested changes
とりあえずmutex回りのコメントしました

2023-03-07 03:15 UTC, t4110 commented on gcloud/logging/structured_logging.go
> +	lg.mu.Lock()
`log.Logger` 内部でmutex持っているので、 `lg.logger` の操作しかしない場合にmutexロックするのは冗長なので削除してもいいかと思います

2023-03-07 03:15 UTC, t4110 commented on gcloud/logging/structured_logging.go
> +	mu         sync.Mutex
このMutexの役割は `entry`, `labelFuncs` の読み書きの排他制御である認識です
(`logger`は内部にMutexを持っているので外から排他制御してやる必要はない、パフォーマンス的にはしない方が良い)

これらはwrite(Set**時)よりread(print時)の方が多いと思うので、 RWMutex を使用したほうがパフォーマンスが良くなると思いますがいかがでしょうか?

2023-03-07 05:20 UTC, ynn1e commented on gcloud/logging/structured_logging.go
> +	mu         sync.Mutex
はい、そのように思います。
修正します。

2023-03-07 05:59 UTC, t4110 approved these changes
LGTM :ok_hand:

2023-03-08 01:23 UTC, merged