Upgrade Google Ads API Client to Version v16
TeamMomentum/go-pkg pull request #9
Opened 2024-07-03 06:07 UTC by Momentakanobu

2024-07-05 06:01 UTC, vortispy commented
@Momentakanobu 
どういうPull Requestか説明の記述お願いします 🙏

2024-07-12 05:00 UTC, Momentakanobu commented
@vortispy 
make v16を実行したところ拡張子goファイル以外にgo-eのファイルが作成された。
goとgo-eの違いは以下の通りとなっているが、これは正しい結果でしょうか？
```
ad_asset.pb.go: enums "github.com/dictav/go-genproto-googleads/pb/v16/enums"
ad_asset.pb.go-e: enums "google.golang.org/genproto/googleapis/ads/googleads/v16/enums"
```

2024-08-06 01:55 UTC, vortispy commented on go-genproto-googleads/Makefile
> +# PKG := github.com/dictav/go-genproto-googleads
不要な行なので消しましょう

2024-08-06 02:09 UTC, vortispy requested changes

2024-08-06 02:09 UTC, vortispy commented on go-genproto-googleads/Makefile
> +TARGETS := v15 v16 v17
`v16`は生成していないので消してしまいましょう。
また`v15`もこちらのパッケージでは使わないので消しましょう。関連ファイルの削除もお願いします。

2024-08-06 02:09 UTC, vortispy commented on go-genproto-googleads/go.mod
> +module github.com/dictav/go-genproto-googleads
ここも変更お願いします。

2024-08-06 05:13 UTC, GiTakanobu commented on go-genproto-googleads/Makefile
> +# PKG := github.com/dictav/go-genproto-googleads
対応しました

2024-08-06 05:13 UTC, GiTakanobu commented on go-genproto-googleads/Makefile
> +TARGETS := v15 v16 v17
対応しました

2024-08-06 05:13 UTC, GiTakanobu commented on go-genproto-googleads/go.mod
> +module github.com/dictav/go-genproto-googleads
対応しました

2024-08-06 08:48 UTC, vortispy commented on go-genproto-googleads/Makefile
> +TARGETS := v15 v16 v17
`/pb/v15`, `/v15`フォルダの削除もお願いします。

2024-08-07 00:49 UTC, Momentakanobu commented on go-genproto-googleads/Makefile
> +TARGETS := v15 v16 v17
削除しました

2024-08-14 05:48 UTC, vortispy requested changes
Apacheライセンスへの対応としてhttps://github.com/dictav/go-genproto-googleads から変更したファイルの先頭に変更したことをコメントで記載してください。
おそらくこんな感じでいいです。
```
// copy from https://github.com/dictav/go-genproto-googleads
// and changed by TeamMomentum
```

2024-08-21 06:10 UTC, Momentakanobu commented
> Apacheライセンスへの対応としてhttps://github.com/dictav/go-genproto-googleads から変更したファイルの先頭に変更したことをコメントで記載してください。 おそらくこんな感じでいいです。
> 
> ```
> // copy from https://github.com/dictav/go-genproto-googleads
> // and changed by TeamMomentum
> ```

コメント対応しました。

2024-08-21 06:46 UTC, vortispy requested changes
すみません。私の説明が悪かったです。
protoファイルから生成された`/v17`,`/pb/v17`のファイルに関してはコメント追加する必要ありません。
コメント追加が必要なのは変更を加えた`Makefile`くらいだと思います。

2024-08-21 06:46 UTC, vortispy commented on .gitignore
> +backup
ルートの`.gitignore`ですが何をignoreしているんでしょうか?

2024-08-27 05:03 UTC, Momentakanobu commented on .gitignore
> +backup
こちらも、戻しました。

2024-08-28 08:49 UTC, vortispy approved these changes

2024-08-30 05:31 UTC, miukoba commented on go-genproto-googleads/README.md
> +I forked [googleapis/googleapis] and wrote patches for building Go Client of Google Ads API [here](https://github.com/dictav/googleapis).
v18のときに困らないようにREADMEも直してほしいです

examples 配下も github.com/dictav/go-genproto-googleads/ を使用したままなので直してほしいです。
ただ別のpull req にしたほうが分かりやすいとおもうので、別途で良いかと思います。

2024-09-06 05:04 UTC, miukoba approved these changes

2024-09-12 02:58 UTC, merged